### ISSUE TITLE
Issues with search polish

### ISSUE THREAD

**Issue by uschiLaa** [ggobi/tourr#71]
- It looks like we can set n_sample but this is not being used, so currently it only samples a small number of planes.
- Breaks when tourr.verbose is not set, example:

> animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish))
Converting input data to the required matrix format.
Press Esc to stop tour running
alpha gets updated to 0.475 
better basis found, index_val =  0.4812705 
alpha gets updated to 0.4286875 
alpha gets updated to 0.3675459 
alpha gets updated to 0.2993685 
alpha gets updated to 0.2316456 
alpha gets updated to 0.1702808 
alpha gets updated to 0.1189134 
better basis found, index_val =  0.4816502 
alpha gets updated to 0.07888961 
alpha gets updated to 0.04972013 
better basis found, index_val =  0.481752 
alpha gets updated to 0.02976928 
better basis found, index_val =  0.4817625 
better basis found, index_val =  0.4817818 
alpha gets updated to 0.01693277 
alpha gets updated to 0.009149792 
alpha is 0.009149792 and it is too small! 
Error in if (getOption("tourr.verbose")) { : argument is of length zero

**Comment by uschiLaa** [comment]
Once the tourr.verbose option is set I also get this error:

Error in proj[[-1]] : invalid negative subscript in get1index <real>

**Comment by uschiLaa** [comment]
Reminder: currently relies on global state, can only run once without clearing the environment.

**Comment by huizezhang-sherry** [comment]
Both have been fixed in the recent PR #72 

1) `getOption()` has a default value of `FALSE`
2) `proj[[-1]]` -> `tail(proj, 1)`
3) global variables have been cleared after each run while `index` is left for possible further reuse

**Comment by sa-lee** [comment]
I'm still unclear why there is an entanglement of the record object and the optimisation? I would think you want to have it so if you have the record option set to FALSE the search functions break? I get the same error with both options

``` r
remotes::install_github("ggobi/tourr")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo ggobi/tourr@HEAD
#> digest   (0.6.25 -> 0.6.27) [CRAN]
#> magrittr (1.5    -> 2.0.1 ) [CRAN]
#> vctrs    (0.3.4  -> 0.3.5 ) [CRAN]
#> R6       (2.4.1  -> 2.5.0 ) [CRAN]
#> generics (0.0.2  -> 0.1.0 ) [CRAN]
#> Installing 5 packages: digest, magrittr, vctrs, R6, generics
#> 
#>   There are binary versions available but the source versions are later:
#>          binary source needs_compilation
#> magrittr    1.5  2.0.1              TRUE
#> vctrs     0.3.4  0.3.5              TRUE
#> 
#> 
#> The downloaded binary packages are in
#>  /var/folders/39/fpr4jmqd3v5cs616xqss63rm0000gq/T//Rtmp3NiOCm/downloaded_packages
#> installing the source packages 'magrittr', 'vctrs'
#>      checking for file ‘/private/var/folders/39/fpr4jmqd3v5cs616xqss63rm0000gq/T/Rtmp3NiOCm/remotes6e1b27c05594/ggobi-tourr-5a9afc7/DESCRIPTION’ ...  ✓  checking for file ‘/private/var/folders/39/fpr4jmqd3v5cs616xqss63rm0000gq/T/Rtmp3NiOCm/remotes6e1b27c05594/ggobi-tourr-5a9afc7/DESCRIPTION’
#>   ─  preparing ‘tourr’: (490ms)
#>      checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘tourr_0.5.9.tar.gz’
#>      
#> 
library(tourr)
animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish))
#> Converting input data to the required matrix format.
#> Error in lapply(1:n_sample, function(x) {: promise already under evaluation: recursive default argument reference or earlier problems?
options(tour.verbose = TRUE)
animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish))
#> Converting input data to the required matrix format.
#> Error in lapply(1:n_sample, function(x) {: promise already under evaluation: recursive default argument reference or earlier problems?
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by huizezhang-sherry** [comment]
1. There is a misspelling in the `options()`: `tourr.verbose = TRUE` with double r

2. `search_polish` should always be used after another `search_*` method. It asks for the supply of a basis from the previous search and makes improvements on top of it 

3. I looked at that `n_sample` problem yesterday but haven't put a PR for that. My branch `ready-for-cran2` has this fixed. 

4. An example code for using `search_polish` with `flea[,1:3]` is 
``` r
#remotes::install_github("huizezhang-sherry/tourr", ref = "ready-for-cran2")
library(tourr) 
library(ferrn)
options(tourr.verbose = TRUE)
```

``` r
set.seed(2020)
better <- animate_xy(flea[, 1:3], 
                     guided_tour(holes(), search_f = search_better))
#> target_dist - cur_dist: 0 
#> Old 0.3716576 
#> New 0.4514259 try 2 
#> generation:  dist =   1.213952
#> target_dist - cur_dist: 1.213952

last <- get_best(better)$basis %>% .[[1]]

set.seed(2020)
polish <- animate_xy(flea[, 1:3], 
                     guided_tour(holes(), search_f = search_polish), 
                     start = last)
#> target_dist - cur_dist: 0 
#> better basis found, index_val =  0.442442 
#> alpha gets updated to 0.475 
#> alpha gets updated to 0.4286875 
#> better basis found, index_val =  0.4726459 
#> alpha gets updated to 0.3675459 
#> better basis found, index_val =  0.474604 
#> alpha gets updated to 0.2993685 
#> better basis found, index_val =  0.4774357 
#> alpha gets updated to 0.2316456 
#> alpha gets updated to 0.1702808 
#> better basis found, index_val =  0.4799891 
#> better basis found, index_val =  0.4812708 
#> alpha gets updated to 0.1189134 
#> alpha gets updated to 0.07888961 
#> better basis found, index_val =  0.4816851 
#> alpha gets updated to 0.04972013 
#> better basis found, index_val =  0.4817157 
#> better basis found, index_val =  0.4817863 
#> alpha gets updated to 0.02976928 
#> alpha gets updated to 0.01693277 
#> alpha gets updated to 0.009149792 
#> alpha is 0.009149792 and it is too small! 
#> current basis:  0.2366155 -0.6634292 -0.7098414 -0.9713944 -0.1463796 -0.1869918 cur_index:  0.4817863 
#> generation:  dist =   1.274483
#> target_dist - cur_dist: 1.274483
```

``` r
get_best(better)
#> # A tibble: 1 x 8
#>   basis             index_val tries info           loop method       alpha    id
#>   <list>                <dbl> <dbl> <chr>         <dbl> <chr>        <dbl> <int>
#> 1 <dbl[,2] [3 × 2]>     0.391     2 interpolation     2 search_bett…    NA     5
get_best(polish)
#> # A tibble: 1 x 8
#>   basis             index_val tries info           loop method       alpha    id
#>   <list>                <dbl> <dbl> <chr>         <dbl> <chr>        <dbl> <int>
#> 1 <dbl[,2] [3 × 2]>     0.400     2 interpolation     2 search_poli…    NA   137
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sa-lee** [comment]
Ok that makes sense. If I set the correct option you still get the error.

I would imagine that you want to catch this in the search_polish function. If you don't supply a start you should pick a reasonable default or throw a more reasonable error telling the user that they should run another search first

**Comment by huizezhang-sherry** [comment]
Yea, a better error message is possible

**Comment by huizezhang-sherry** [comment]
The `n_sample` argument is similar to the `counter` in `find_best_dir()` used by the `search_geodesic` . 

I can't find a way to adjust the `counter` argument in the current version.   Since @uschiLaa wants `n_sample` to be adjustable, the only way I can make it work is to add `n_sample` as an argument in `guided_tour()`. 

Quite possible there's a better solution out there ...

**Comment by dicook** [comment]
this was still creating an error because the record saving was happening outside of an if verbose statement. fixed now. in commit 06d764b

**Comment by dicook** [comment]
But still having an issue trying to use it with a starting basis:

> b <- basis_random(n=6)
> animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish), start = b)
Converting input data to the required matrix format.
Press Esc to stop tour running
Error: Problem with `mutate()` input `index_val`.
x non-conformable arguments
ℹ Input `index_val` is `vapply(basis, function(x) index(x), double(1))`.
Run `rlang::last_error()` to see where the error occurred.

> animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish), start = b, index = 0)
Converting input data to the required matrix format.
Press Esc to stop tour running
Error in try <= polish_max_tries : 
  comparison (4) is possible only for atomic and list types

> animate_xy(flea[, 1:3], guided_tour(holes(), search_f = search_polish), start = b, cur_index = 0)
Converting input data to the required matrix format.
Press Esc to stop tour running
Error in search_f(current, alpha, index, max.tries, cur_index = cur_index,  : 
  formal argument "cur_index" matched by multiple actual arguments
